'' Base16 Summerfruit Light color 
'' Author: Christopher Corley (http://christop.club/)
'' to be use in your PlantUML theme

!$BASE00 = "#FFFFFF"  ' ----
!$BASE01 = "#E0E0E0"  ' ---
!$BASE02 = "#D0D0D0"  ' --
!$BASE03 = "#B0B0B0"  ' -
!$BASE04 = "#000000"  ' +
!$BASE05 = "#101010"  ' ++
!$BASE06 = "#151515"  ' +++
!$BASE07 = "#202020"  ' ++++
!$BASE08 = "#FF0086"  ' red
!$BASE09 = "#FD8900"  ' orange
!$BASE0A = "#ABA800"  ' yellow
!$BASE0B = "#00C918"  ' green
!$BASE0C = "#1FAAAA"  ' aqua/cyan
!$BASE0D = "#3777E6"  ' blue
!$BASE0E = "#AD00A1"  ' purple
!$BASE0F = "#CC6633"  ' brown