'' Base16 Horizon Dark color 
'' Author: Michaël Ball (http://github.com/michael-ball/)
'' to be use in your PlantUML theme

!$BASE00 = "#1C1E26"  ' ----
!$BASE01 = "#232530"  ' ---
!$BASE02 = "#2E303E"  ' --
!$BASE03 = "#6F6F70"  ' -
!$BASE04 = "#9DA0A2"  ' +
!$BASE05 = "#CBCED0"  ' ++
!$BASE06 = "#DCDFE4"  ' +++
!$BASE07 = "#E3E6EE"  ' ++++
!$BASE08 = "#E93C58"  ' red
!$BASE09 = "#E58D7D"  ' orange
!$BASE0A = "#EFB993"  ' yellow
!$BASE0B = "#EFAF8E"  ' green
!$BASE0C = "#24A8B4"  ' aqua/cyan
!$BASE0D = "#DF5273"  ' blue
!$BASE0E = "#B072D1"  ' purple
!$BASE0F = "#E4A382"  ' brown