'' Base16 Atelier Dune Light color 
'' Author: Bram de Haan (http://atelierbramdehaan.nl)
'' to be use in your PlantUML theme

!$BASE00 = "#fefbec"  ' ----
!$BASE01 = "#e8e4cf"  ' ---
!$BASE02 = "#a6a28c"  ' --
!$BASE03 = "#999580"  ' -
!$BASE04 = "#7d7a68"  ' +
!$BASE05 = "#6e6b5e"  ' ++
!$BASE06 = "#292824"  ' +++
!$BASE07 = "#20201d"  ' ++++
!$BASE08 = "#d73737"  ' red
!$BASE09 = "#b65611"  ' orange
!$BASE0A = "#ae9513"  ' yellow
!$BASE0B = "#60ac39"  ' green
!$BASE0C = "#1fad83"  ' aqua/cyan
!$BASE0D = "#6684e1"  ' blue
!$BASE0E = "#b854d4"  ' purple
!$BASE0F = "#d43552"  ' brown