'' Base16 Classic Dark color 
'' Author: Jason Heeris (http://heeris.id.au)
'' to be use in your PlantUML theme

!$BASE00 = "#151515"  /' ----      '/
!$BASE01 = "#202020"  /' ---       '/
!$BASE02 = "#303030"  /' --        '/
!$BASE03 = "#505050"  /' -         '/
!$BASE04 = "#B0B0B0"  /' +         '/
!$BASE05 = "#D0D0D0"  /' ++        '/
!$BASE06 = "#E0E0E0"  /' +++       '/
!$BASE07 = "#F5F5F5"  /' ++++      '/
!$BASE08 = "#AC4142"  /' red       '/
!$BASE09 = "#D28445"  /' orange    '/
!$BASE0A = "#F4BF75"  /' yellow    '/
!$BASE0B = "#90A959"  /' green     '/
!$BASE0C = "#75B5AA"  /' aqua/cyan '/
!$BASE0D = "#6A9FB5"  /' blue      '/
!$BASE0E = "#AA759F"  /' purple    '/
!$BASE0F = "#8F5536"  /' brown     '/
