'' Base16 PaperColor Light color 
'' Author: Jon Leopard (http://github.com/jonleopard) based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)
'' to be use in your PlantUML theme

!$BASE00 = "#eeeeee"  /' ----      '/
!$BASE01 = "#af0000"  /' ---       '/
!$BASE02 = "#008700"  /' --        '/
!$BASE03 = "#5f8700"  /' -         '/
!$BASE04 = "#0087af"  /' +         '/
!$BASE05 = "#444444"  /' ++        '/
!$BASE06 = "#005f87"  /' +++       '/
!$BASE07 = "#878787"  /' ++++      '/
!$BASE08 = "#bcbcbc"  /' red       '/
!$BASE09 = "#d70000"  /' orange    '/
!$BASE0A = "#d70087"  /' yellow    '/
!$BASE0B = "#8700af"  /' green     '/
!$BASE0C = "#d75f00"  /' aqua/cyan '/
!$BASE0D = "#d75f00"  /' blue      '/
!$BASE0E = "#005faf"  /' purple    '/
!$BASE0F = "#005f87"  /' brown     '/
